[project]
name = "ha-es"
version = "0.1.0"
requires-python = ">=3.10"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "memory-profiler>=0.61.0",
    "pandas>=2.3.1",
]
